[package]
name = "wasmer-examples/mkdocs-wasmer-starter"
version = "0.2.0"
description = "Mkdocs Wasmer starter package"
readme = "README.md"
repository = "https://github.com/wasmer-examples/mkdocs-wasmer-starter"

[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
public = "site"
