name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ github.token }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_deploy_mkdocs:
    name: Build and Deploy MKDocs based static site to Wasmer Edge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Wasmer
        uses: wasmerio/setup-wasmer@v2
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install mkdocs
        run: pip install mkdocs
      - name: Build MKdocs
        run: mkdocs build
      - name: Deploy app to Wasmer Edge
        run: wasmer deploy --token=${{ secrets.WASMER_CIUSER_PROD_TOKEN }} --publish-package --non-interactive --no-wait --no-persist-id
